nacos:
  config:
    bootstrap:
      enable: true
    server-addr: nacos.cnheri.com
    data-id: service-consumer
    group: hello-dubbo
    namespace: test
    type: yaml
    auto-refresh: true
    config-retry-time: 2333
    config-long-poll-timeout: 46000
