spring:
  application:
    name: hello-dubbo-service-consumer
server:
  port: 8080
nacos:
  host: nacos.cnheri.com
  port: 80
  username: nacos
  password: Ljb314159265
dubbo:
  scan:
    base-packages: com.binhow.hello.dubbo.service.consumer.controller
  protocol:
    name: dubbo
    port: 8801
  registry:
    address: nacos://${nacos.host}:${nacos.port}/?username=${nacos.username}&password=${nacos.password}

user:
  service:
    version: 1.0.0-SNAPSHOT

